### ISSUE TITLE
Particularities with ufo-kit on Ubuntu 18.04 (64-bit)

### ISSUE THREAD

**Issue by mikcieslak** [ufo-kit/tofu#98] opened 2020-04-02 05:09 UTC
Hi,
I am using the latest ufo-kit and tofu (with the E&Z ufo-kit from the CLS) on Ubuntu 18.04 (64-bit). It is working but I had a couple of minor issues, which I was hoping the developers could address:

(1) The laminographic backprojection filter called via tofu (in \_setup_graph(), lamino.py) throws a TypeError exception. I believe it is caused in the specification of the 'backproject.props.region = region' call. I implemented a workaround by type casting the elements of the 'region' array as 'float', and modifying the corresponding variable in ufo-lamino-backproject-task.c: GParamSpec *float_region_vals = g_param_spec_**double** (to match Python's double precision float). I was hoping there was a better solution that does not require changing the ufo-filter.

(2) There is some strange issue with the multi-page tiff file output in the following sequence of calls:
$ tofu preprocess --fix-nan-and-inf --projection-filter none --darks /darks --flats /flats --projections /tomo --output /proj/proj-%04i.tif --energy 20.0 --propagation-distance 0.05 --pixel-size 3.6e-06 --regularization-rate 2.47712125472
$ tofu sinos --projections /proj --output /sinos/sin-%04i.tif --y 500 --height 100 --y-step 1
The first call (to preprocess) produces a multi-page tif file that looks like you'd expect, but the second call (to sinos) produces a multi-page tif file that is unexpected. Each image is just many vertical lines. I modified the call to tofu preprocess to output a sequence of images instead of a multi-page tiff and then the second call produced what I expected. (The temporary workaround is to add "out_task.set_properties(bytes_per_file=0, tiff_bigtiff=False)" in run_preprocessing() in preprocess.py)

(3) The ufo-launch command doesn't warn you if you give the same file name for the input and output command line arguments. This is not an issue for a sequence of images, but causes a bus error if multi-page tiff files are used. Or instead of a warning, maybe it is possible to use a mutex.

Thanks in advance for your help!

**Comment by tfarago** [comment] 2020-04-02 06:27
You need to tell `tofu sinos` how many projections are there like this: `tofu sinos --number NUM_PROJS ...`

**Comment by mikcieslak** [comment] 2020-04-02 21:02
Great, thanks for the quick reply.

(1) The tofu command (from CLS's EZ_ufo script) is:
$ tofu lamino --absorptivity --fix-nan-and-inf --overall-angle 180 --lamino-angle 90 --height 2 --darks ./darks --flats ./flats --projections ./tomo --output ./slice --x-region=-128,128,1 --y-region=-128,128,1 --y 1000 --height 2 --z-parameter x-center --region="1010,1030,0.5" --z 0 --axis 1020.0,1.0
It is being used to find the centre of rotation. I will look into using tofu reco instead.

(2) Too easy! I should have asked sooner ;)

(3) Hehe, users can't be trusted.

**Comment by tfarago** [comment] 2020-04-03 10:16
Can you send me the error when you type this in the interpreter please?
```python
from gi.repository import Ufo
pm = Ufo.PluginManager()
t = pm.get_task('lamino-backproject')
t.props.region = [1010, 1030, 0.5]
```
For me it works fine. If you get an error, please send me the versions of python and all the UFO prerequisite libraries. Thanks.

**Comment by mikcieslak** [comment] 2020-04-05 04:21
If I run the test Python code, I get the following warning:
> Warning: value "((GValueArray*) 0x5574dd334ce0)" of type 'GValueArray' is invalid or out of range for property 'region' of type 'GValueArray'
t.props.region = [1010, 1030, 0.5]

And if I print the values of region:
`print t.props.region[0], t.props.region[1], t.props.region[2]`,
the output is:
> 0.0 0.0 0.0

If I cast the elements to float:
`t.props.region = [float(1010), float(1030), float(0.5)]`, and
change g_param_spec_**float** to **double** in GParamSpec *float_region_vals in ufo-lamino-backproject-task.c, the output of running the Python code with the print statement is:
> 1010.0 1030.0 0.5

(If I don't change from float to double in ufo-lamino-backproject-task.c, I get the same warning and the output is all zeros again.)

I'm surprised about the warning with GValueArray. Anyway, here are the version numbers:
Python 2.7.17 (libpython-dev:amd64, 2.7.15~rc1-1)
GLib 2.0 (libglib2.0-dev:amd64, 2.56.4-0ubuntu0.18.04.6)
GObject 1.0 (libgirepository1.0-dev:amd64, 1.56.1-1)
libtiff5-dev:amd64, 4.0.9-5ubuntu0.3

**Comment by tfarago** [comment] 2020-04-06 12:05
I installed those package versions and still can't reproduce your problem. Can you tell me the version of gobject-introspection please?

**Comment by mikcieslak** [comment] 2020-04-06 17:02
Yes, here it is:
gobject-introspection/bionic,now 1.56.1-1 amd64 

Also, I'm not sure if you need to know any of these:
python-gobject/bionic-updates,bionic-updates 3.26.1-2ubuntu1 all
python-gobject-2/bionic 2.28.6-12ubuntu3 amd64
python-gobject-2-dbg/bionic 2.28.6-12ubuntu3 amd64
python-gobject-2-dev/bionic,bionic 2.28.6-12ubuntu3 all

**Comment by tfarago** [comment] 2020-04-08 11:07
I have the exact same versions and don't see this happening. when you start your python interpreter, what version is it? I mean really python, not python-dev.

**Comment by mikcieslak** [comment] 2020-04-09 03:52
`$ python`
> Python 2.7.17 (default, Nov  7 2019, 10:07:09) 
[GCC 7.4.0] on linux2

`$ python --version`
`Python 2.7.17`

And in case it is helpful:
`$ gcc --version`
`gcc (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0`

Here is the link.txt file in the ufofilterlaminobackproject.dir:
` /usr/bin/cc -fPIC  -std=gnu99 -pedantic -Wall -Wextra -fPIC -Wno-unused-parameter -Wno-deprecated-declarations -fopenmp  -shared -Wl,-soname,libufofilterlaminobackproject.so -o libufofilterlaminobackproject.so CMakeFiles/ufofilterlaminobackproject.dir/ufo-lamino-backproject-task.c.o CMakeFiles/ufofilterlaminobackproject.dir/lamino-roi.c.o  -lm -lufo -lgmodule-2.0 -ljson-glib-1.0 -lgio-2.0 -lgobject-2.0 -lglib-2.0 -lOpenCL libufoaux.a `

Maybe I've made a mistake in compiling the ufo-kit filters...?

**Comment by tfarago** [comment] 2020-04-09 15:52
For some reason I have a different python interpreter version, I will try to update and get back to you in one week, I am not here until then.

**Comment by tfarago** [comment] 2020-04-22 08:51
I have the exact same version of Python and gcc now. However, did you notice that when you start python it doesn't list the 7.5.0 version of gcc?
How did you compile ufo-filters please, cmake?

**Comment by mikcieslak** [comment] 2020-04-23 00:15
Yes, I see. I updated Python 2 and now the interpreter lists GCC 7.5.0:
> Python 2.7.17 (default, Apr 15 2020, 17:20:14) 
[GCC 7.5.0] on linux2

 but I get the same behaviour as before: if I run your test code for the 'lamino-backproject' filter, I get a warning and all values of region are zero. 

Yes, I compiled ufo-filters using cmake. I followed the instructions from the ufo-core manual, Section "Installing from source".

**Comment by tfarago** [comment] 2020-04-30 11:24
Could you please switch to branch ` lamino-double-gvaluearray ` of ufo-filters? I just pushed the `double` code. Then please use the floating point numbers where necessary in the tofu commands on the command line (e.g. --region=1.0,2.0,0.5) and let me know if it works.

**Comment by mikcieslak** [comment] 2020-05-01 06:48
I switched to branch `lamino-double-gvaluearray`, recompiled ufo-filters, and retried the Python test code with the region defined as `t.props.region = [1010.0, 1030.0, 0.5]`. It works as expected (no warnings). 

By the way, I think I've found another part of tofu that has a similar issue. I was using the `tofu reco` command and was getting the following warnings:

> /usr/local/lib/python2.7/dist-packages/tofu-0.9-py2.7.egg/tofu/genreco.py:231: Warning: value "((GValueArray*) 0x7f47cc009520)" of type 'GValueArray' is invalid or out of range for property 'x-region' of type 'GValueArray'
/usr/local/lib/python2.7/dist-packages/tofu-0.9-py2.7.egg/tofu/genreco.py:232: Warning: value "((GValueArray*) 0x7f47cc009560)" of type 'GValueArray' is invalid or out of range for property 'y-region' of type 'GValueArray'

I tracked this warning to a call to the `ufo-general-backproject-task`, which uses double for the x-region and y-region parameters. To "fix" it, I added a type conversion in the 'get_reconstruction_regions()' function of util.py (just before the values are stored and returned):
`x_region = [float(i) for i in x_region]`
`y_region = [float(i) for i in y_region]`

Anyway, I'm not sure if this issue is related to Ubuntu 18.04 in general or just to my installation in particular...so thanks for looking into it.

**Comment by tfarago** [comment] 2020-05-04 10:53
If you pull on tofu's master you should not see the warnings anymore. `lamino` code can't supersample the output, so the slice region is integer but with the `reco` supersampling was added recently and this was a leftover from the times where the two codes were the same. Thanks for pointing it out.

Since I have the exact same package versions as you I don't see where the warnings come from. It seems to me that my glib just tries harder to convert the data to the expected data type. If I type `t.props.region = [int(1), int(2), int(3)]` I get `[1.0, 2.0, 3.0]` as a result. Of course this is strictly speaking wrong behavior. And since our glib's and the rest of the packages are the same I don't know where this different behavior comes from. Perhaps it's some setting somewhere...

**Comment by tfarago** [comment] 2020-05-07 08:30
Does it work? If yes I'd close this issue.

**Comment by mikcieslak** [comment] 2020-05-07 17:44
Yes, thanks! One last quick note: I had to set 'tifffile==2019.7.26.2' in tofu's setup.py because the newer version gave me an invalid syntax error.
Thanks again for all your help.

**Closed** 2020-05-07 17:45 UTC
